# Title     : FMS
# Objective : Mode Jumping MCMC algorithm
# Created by: jonlachmann
# Created on: 2021-04-27

#' Main Algorithm for FMS (Genetically Modified FMS)
#'
#' @param x matrix containing the design matrix with data to use in the algorithm,
#' @param y response variable
#' @param N The number of FMS iterations to run for (default 100)
#' @param probs A list of various probability vectors used by FFMS, generated by \code{gen.probs.fms_base}. 
#' @param params A list of various parameter vectors used by FMS, generated by \code{gen.params.fms_base}.
#' @param loglik.pi A function specifying the marginal log-posterior of the model up to a constant, including the logarithm of the model prior:
#'   \eqn{\log p(M|Y) = \text{const} + \log p(Y|M) + \log p(M)}.
#'   Typically assumes a Gaussian model with Zellner's g prior with \eqn{g = max(n,p^2) by default}.
#' @param mlpost_params All parameters for the estimator function loglik.pi
#' @param intercept Logical. Whether to include an intercept in the design matrix. Default is \code{TRUE}. No variable selection is performed on the intercept.
#' @param fixed Integer specifying the number of leading columns in the design matrix to always include in the model. Default is 0.
#' @param sub Logical. If \code{TRUE}, uses subsampling or a stochastic approximation approach to the likelihood rather than the full likelihood. Default is \code{FALSE}. 
#' @param verbose Logical. Whether to print messages during execution. Default is \code{TRUE} for \code{ffms_base} and \code{FALSE} for the parallel version.
#'
#' @return A list containing the following elements:
#' \item{models}{All visited models in both fms_base and local optimization.}
#' \item{accept}{Average acceptance rate of the chain.}
#' \item{mc.models}{All models visited during fms_base iterations.}
#' \item{best.crit}{The highest log marginal probability of the visited models.}
#' \item{sic.probs}{Marginal probabilities of the features.}
#' \item{model.probs}{Marginal probabilities of all of the visited models.}
#' \item{model.probs.idx}{Indices of unique visited models.}
#' \item{populations}{The covariates represented as a list of features.}
#'
#' @examples
#' result <- fms_base(
#' y = matrix(rnorm(100), 100),
#' x = matrix(rnorm(600), 100),
#' loglik.pi = gaussian.loglik)
#' summary(result)
#' plot(result)
#'
#' @export fms_base
fms_base <- function (
  x,
  y,
  N = 1000,
  probs = NULL,
  params = NULL,
  loglik.pi = NULL,
  mlpost_params = list(family = "gaussian", beta_prior = list(type = "g-prior")),
  intercept = TRUE,
  fixed = 0,
  sub = FALSE,
  verbose = TRUE
) {
  # Verify that data is well-formed
  if (intercept) {
    x <- cbind(1, x)
    fixed <- fixed + 1
  }
  data <- check.data(x, y, fixed, verbose)
  
  if(is.null(loglik.pi))
  {
    if (is.null(mlpost_params$family)) {
      mlpost_params$family <- "gaussian"
    }
    loglik.pi <- sic.loglik
  }
  
  labels <- colnames(x)
  if (fixed != 0)
    labels <- labels[-seq_len(fixed)]

  # Generate default probabilities and parameters if there are none supplied.
  if (is.null(probs)) probs <- gen.probs.fms_base()
  if (is.null(params)) params <- gen.params.fms_base(ncol(data$x) - data$fixed)
  if (!is.null(mlpost_params)) params$mlpost <- mlpost_params

  # Acceptance probability
  accept <- 0

  # Create a population of just the covariates
  S <- gen.covariates(data)
  complex <- complex.features(S)

  # Initialize first model
  model.cur <- as.logical(rbinom(n = length(S), size = 1, prob = 0.5))
  model.cur.res <- loglik.pre(loglik.pi, model.cur, complex, data, params$mlpost, visited.models = NULL, sub = sub)
  model.cur <- list(prob = 0, model = model.cur, coefs = model.cur.res$coefs, crit = model.cur.res$crit, alpha = 0)

  if (verbose) cat("\nFMS begin.\n")
  result <- sic_optimize.loop(data, complex, loglik.pi, model.cur, N, probs, params, sub, verbose)
  if (verbose) cat("\nFMS done.\n")
  # Calculate acceptance rate
  result$accept <- result$accept / N
  result$populations <- S

  # Return formatted results
  result$fixed <- data$fixed
  result$labels <- labels
  result$intercept <- intercept
  class(result) <- "fms_base"
  return(result)
}

